name: cfrn
description: "Canada first radio ntm"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  audioplayers: ^6.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  shared_preferences: ^2.2.3
  reorderables: ^0.6.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/radio.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/radio.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
